### ISSUE TITLE
Removal Request, UW Homework Solutions

### ISSUE THREAD

**Issue by jsanders89** [truedoomboom/CSE143_HW2_GuitarHero#1]
Hi Artiom,

My name is Jonathan and I work with the University of Washington's intro computer science courses.  Your solutions to CSE 143's homework assignments are available on your GitHub page here:

https://github.com/truedoomboom/CSE143_HW2_GuitarHero/tree/master/src
https://github.com/truedoomboom/CSE143_HW3_Assassin/blob/master/src/AssassinManager.java
https://github.com/truedoomboom/CSE143_HW4_EvilHangman/blob/master/src/HangmanManager.java
https://github.com/truedoomboom/CSE143_HW5_GrammarSolver
https://github.com/truedoomboom/CSE143_HW6_Anagrams/blob/master/src/Anagrams.java
https://github.com/truedoomboom/CSE143_HW7_20Questions/tree/master/src

These posts are indexed by Github's search which enables our current students to easily find them and submit them as their own work.

Would you be willing to remove those posts from your GitHub in order to help us enforce our academic policy?

Best,
Jonathan Sanders
CSE 14X Program Coordinator

**Comment by truedoomboom** [comment]
Hi Jonathan,
I prefer to keep my repositories here as opposed to my local machine. Since universities in US use plagiarism checker tools on student's solutions, I am sure it's not too difficult to add mine to the list.
Also I highly doubt that your students would get high scores from my solutions.
